import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import IconArrowDown from '../components/IconArrowDown';
import { navigationData, clientData } from '../data';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>
          Intro section with dropdown navigation website | frontendmentor.io
          challenge
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <header className="fixed top-0 left-0 w-full bg-white p-6 flex items-center justify-between">
        <div className="flex items-center sm:gap-8">
          <Image
            src="/images/logo.svg"
            className="object-contain"
            alt="Logo"
            width={84}
            height={27}
          />

          <nav className="hidden sm:inline-block">
            <ul className="flex items-center gap-4 text-sm md:gap-8">
              {navigationData.map((navigationItem, index) => (
                <li key={index} className="flex items-center gap-1">
                  {navigationItem.title}
                  {navigationItem.subCategories.length > 0 && <IconArrowDown />}
                </li>
              ))}
            </ul>
          </nav>
        </div>

        <div className="hidden text-sm sm:flex sm:items-center md:gap-2 ">
          <button className="py-2 px-6">Login</button>
          <button className="py-2 px-6 border rounded-xl">Register</button>
        </div>

        <div className="sm:hidden">
          <Image
            src="/images/icon-menu.svg"
            alt="Menu icon"
            width={32}
            height={18}
          />
        </div>
      </header>

      <main className="flex flex-col gap-8 sm:flex-row-reverse sm:min-h-screen sm:items-center sm:justify-center">
        <div className="relative w-full h-[45vh] sm:h-[70vh] sm:w-1/2">
          <Image
            src="/images/image-hero-desktop.png"
            alt="Hero"
            className="object-contain"
            layout="fill"
          />
        </div>

        <div className="sm:flex sm:items-center sm:justify-center sm:w-1/2">
          <div className="grid gap-8 p-4 sm:max-w-md">
            <div className="grid gap-4 text-center sm:gap-12 sm:text-left">
              <h1 className="text-4xl font-bold sm:text-7xl">
                Make remote work
              </h1>
              <p>
                Get your team in sync, no matter your location. Streamline
                processes, create team rituals, and watch productivity soar.
              </p>

              <button className="text-white rounded-xl font-bold px-6 py-3 bg-black m-auto sm:m-0 sm:w-32 sm:px-0">
                Learn more
              </button>
            </div>

            <div className="flex items-center justify-between gap-4">
              {clientData.map((client, index) => (
                <Image
                  key={index}
                  src={client.src}
                  alt={`Client ${client.name}`}
                  width={client.width}
                  height={client.height}
                />
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
