import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>
          Intro section with dropdown navigation website | frontendmentor.io
          challenge
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>

      <main>Hello, world!</main>
    </div>
  );
};

export default Home;
